import { Person } from '../src/types/queryProps'

export const peopleData: Person[] = [
  {
    _id: '0',
    firstname: 'John',
    lastname: 'Doe',
    gender: 'Male',
    height: '180',
    haircolor: 'Brown',
    weight: '75',
    skincolor: 'Fair',
    ethnicity: 'Caucasian',
    language: 'English',
    city: 'New York',
    address: '123 Main St',
    phoneNumber: '123-456-7890',
    email: 'johndoe@example.com',
    pictures: 'https://randomuser.me/api/portraits/men/1.jpg',
    shoeSize: '10',
    waistSize: '32',
    age: '30',
    availability: true,
  },
  {
    _id: '1',
    firstname: 'Jane',
    lastname: 'Smith',
    gender: 'Female',
    height: '165',
    haircolor: 'Blonde',
    weight: '60',
    skincolor: 'Light',
    ethnicity: 'Caucasian',
    language: 'English',
    city: 'Los Angeles',
    address: '456 Elm St',
    phoneNumber: '987-654-3210',
    email: 'janesmith@example.com',
    pictures: 'https://randomuser.me/api/portraits/women/2.jpg',
    shoeSize: '8',
    waistSize: '28',
    age: '25',
    availability: true,
  },
  {
    _id: '2',
    firstname: 'Alex',
    lastname: 'Johnson',
    gender: 'Non-binary',
    height: '170',
    haircolor: 'Purple',
    weight: '65',
    skincolor: 'Medium',
    ethnicity: 'Multiracial',
    language: 'English',
    city: 'San Francisco',
    address: '789 Oak St',
    phoneNumber: '555-123-4567',
    email: 'alexjohnson@example.com',
    pictures: 'https://randomuser.me/api/portraits/lego/3.jpg',
    shoeSize: '9',
    waistSize: '30',
    age: '28',
    availability: true,
  },
  {
    _id: '3',
    firstname: 'Emily',
    lastname: 'Brown',
    gender: 'Female',
    height: '160',
    haircolor: 'Black',
    weight: '55',
    skincolor: 'Dark',
    ethnicity: 'African American',
    language: 'English',
    city: 'Chicago',
    address: '789 Maple Ave',
    phoneNumber: '444-555-6666',
    email: 'emilybrown@example.com',
    pictures: 'https://randomuser.me/api/portraits/women/4.jpg',
    shoeSize: '7',
    waistSize: '26',
    age: '32',
    availability: true,
  },
  {
    _id: '4',
    firstname: 'Michael',
    lastname: 'Johnson',
    gender: 'Male',
    height: '185',
    haircolor: 'Brown',
    weight: '80',
    skincolor: 'Medium',
    ethnicity: 'Hispanic',
    language: 'English, Spanish',
    city: 'Miami',
    address: '555 Palm Blvd',
    phoneNumber: '777-888-9999',
    email: 'michaeljohnson@example.com',
    pictures: 'https://randomuser.me/api/portraits/men/5.jpg',
    shoeSize: '11',
    waistSize: '34',
    age: '40',
    availability: true,
  },
  {
    _id: '5',
    firstname: 'Sophia',
    lastname: 'Davis',
    gender: 'Female',
    height: '170',
    haircolor: 'Red',
    weight: '65',
    skincolor: 'Fair',
    ethnicity: 'Caucasian',
    language: 'English',
    city: 'Seattle',
    address: '222 Oak St',
    phoneNumber: '111-222-3333',
    email: 'sophiadavis@example.com',
    pictures: 'https://randomuser.me/api/portraits/women/6.jpg',
    shoeSize: '9',
    waistSize: '28',
    age: '27',
    availability: true,
  },
]
